version: '2'
networks:
    public:
        driver: bridge
    private:
        driver: bridge

services:
  application:
    image: php:7-apache
    working_dir: /var/www
    entrypoint: /var/www/opt/docker/development/entrypoint
    volumes:
      - ./opt/apache2/development/apache2.conf:/etc/apache2/apache2.conf
      - ./opt/apache2/development/virtual-host.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www
    ports:
      - 10000:80
    networks:
      - public
      - private

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: password
      MYSQL_USER: dbuser
      MYSQL_DATABASE: slim
    networks:
      - public
      - private

  redis:
    image: redis:3.2-alpine
    networks:
      - private
